//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapWinFormsApplication.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity1ViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entity1ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string longitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapWinFormsApplication.ServiceReference.Entity2ViewModel Entity2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.longitudeField, value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.latitudeField, value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MapWinFormsApplication.ServiceReference.Entity2ViewModel Entity2 {
            get {
                return this.Entity2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Entity2Field, value) != true)) {
                    this.Entity2Field = value;
                    this.RaisePropertyChanged("Entity2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity2ViewModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entity2ViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string zoomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapWinFormsApplication.ServiceReference.Entity1ViewModel[] Entity1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string zoom {
            get {
                return this.zoomField;
            }
            set {
                if ((object.ReferenceEquals(this.zoomField, value) != true)) {
                    this.zoomField = value;
                    this.RaisePropertyChanged("zoom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel[] Entity1 {
            get {
                return this.Entity1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Entity1Field, value) != true)) {
                    this.Entity1Field = value;
                    this.RaisePropertyChanged("Entity1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MapWinFormsApplication.ServiceReference.HelloWorldResponse HelloWorld(MapWinFormsApplication.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name deviceName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDevice", ReplyAction="*")]
        MapWinFormsApplication.ServiceReference.AddDeviceResponse AddDevice(MapWinFormsApplication.ServiceReference.AddDeviceRequest request);
        
        // CODEGEN: Generating message contract since element name GetDevicesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevices", ReplyAction="*")]
        MapWinFormsApplication.ServiceReference.GetDevicesResponse GetDevices(MapWinFormsApplication.ServiceReference.GetDevicesRequest request);
        
        // CODEGEN: Generating message contract since element name GetCitiesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCities", ReplyAction="*")]
        MapWinFormsApplication.ServiceReference.GetCitiesResponse GetCities(MapWinFormsApplication.ServiceReference.GetCitiesRequest request);
        
        // CODEGEN: Generating message contract since element name city from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevicesByCity", ReplyAction="*")]
        MapWinFormsApplication.ServiceReference.GetDevicesByCityResponse GetDevicesByCity(MapWinFormsApplication.ServiceReference.GetDevicesByCityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MapWinFormsApplication.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MapWinFormsApplication.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(MapWinFormsApplication.ServiceReference.Entity1ViewModel HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDeviceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDevice", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.AddDeviceRequestBody Body;
        
        public AddDeviceRequest() {
        }
        
        public AddDeviceRequest(MapWinFormsApplication.ServiceReference.AddDeviceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDeviceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deviceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string longitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cityName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string zoomLevel;
        
        public AddDeviceRequestBody() {
        }
        
        public AddDeviceRequestBody(string deviceName, string longitude, string latitude, string cityName, string zoomLevel) {
            this.deviceName = deviceName;
            this.longitude = longitude;
            this.latitude = latitude;
            this.cityName = cityName;
            this.zoomLevel = zoomLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDeviceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDeviceResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.AddDeviceResponseBody Body;
        
        public AddDeviceResponse() {
        }
        
        public AddDeviceResponse(MapWinFormsApplication.ServiceReference.AddDeviceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDeviceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel AddDeviceResult;
        
        public AddDeviceResponseBody() {
        }
        
        public AddDeviceResponseBody(MapWinFormsApplication.ServiceReference.Entity1ViewModel AddDeviceResult) {
            this.AddDeviceResult = AddDeviceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevices", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.GetDevicesRequestBody Body;
        
        public GetDevicesRequest() {
        }
        
        public GetDevicesRequest(MapWinFormsApplication.ServiceReference.GetDevicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDevicesRequestBody {
        
        public GetDevicesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.GetDevicesResponseBody Body;
        
        public GetDevicesResponse() {
        }
        
        public GetDevicesResponse(MapWinFormsApplication.ServiceReference.GetDevicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel[] GetDevicesResult;
        
        public GetDevicesResponseBody() {
        }
        
        public GetDevicesResponseBody(MapWinFormsApplication.ServiceReference.Entity1ViewModel[] GetDevicesResult) {
            this.GetDevicesResult = GetDevicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCities", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.GetCitiesRequestBody Body;
        
        public GetCitiesRequest() {
        }
        
        public GetCitiesRequest(MapWinFormsApplication.ServiceReference.GetCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCitiesRequestBody {
        
        public GetCitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.GetCitiesResponseBody Body;
        
        public GetCitiesResponse() {
        }
        
        public GetCitiesResponse(MapWinFormsApplication.ServiceReference.GetCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapWinFormsApplication.ServiceReference.Entity2ViewModel[] GetCitiesResult;
        
        public GetCitiesResponseBody() {
        }
        
        public GetCitiesResponseBody(MapWinFormsApplication.ServiceReference.Entity2ViewModel[] GetCitiesResult) {
            this.GetCitiesResult = GetCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesByCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesByCity", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.GetDevicesByCityRequestBody Body;
        
        public GetDevicesByCityRequest() {
        }
        
        public GetDevicesByCityRequest(MapWinFormsApplication.ServiceReference.GetDevicesByCityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesByCityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetDevicesByCityRequestBody() {
        }
        
        public GetDevicesByCityRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesByCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesByCityResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapWinFormsApplication.ServiceReference.GetDevicesByCityResponseBody Body;
        
        public GetDevicesByCityResponse() {
        }
        
        public GetDevicesByCityResponse(MapWinFormsApplication.ServiceReference.GetDevicesByCityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesByCityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel[] GetDevicesByCityResult;
        
        public GetDevicesByCityResponseBody() {
        }
        
        public GetDevicesByCityResponseBody(MapWinFormsApplication.ServiceReference.Entity1ViewModel[] GetDevicesByCityResult) {
            this.GetDevicesByCityResult = GetDevicesByCityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MapWinFormsApplication.ServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MapWinFormsApplication.ServiceReference.WebServiceSoap>, MapWinFormsApplication.ServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapWinFormsApplication.ServiceReference.HelloWorldResponse MapWinFormsApplication.ServiceReference.WebServiceSoap.HelloWorld(MapWinFormsApplication.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel HelloWorld() {
            MapWinFormsApplication.ServiceReference.HelloWorldRequest inValue = new MapWinFormsApplication.ServiceReference.HelloWorldRequest();
            inValue.Body = new MapWinFormsApplication.ServiceReference.HelloWorldRequestBody();
            MapWinFormsApplication.ServiceReference.HelloWorldResponse retVal = ((MapWinFormsApplication.ServiceReference.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapWinFormsApplication.ServiceReference.AddDeviceResponse MapWinFormsApplication.ServiceReference.WebServiceSoap.AddDevice(MapWinFormsApplication.ServiceReference.AddDeviceRequest request) {
            return base.Channel.AddDevice(request);
        }
        
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel AddDevice(string deviceName, string longitude, string latitude, string cityName, string zoomLevel) {
            MapWinFormsApplication.ServiceReference.AddDeviceRequest inValue = new MapWinFormsApplication.ServiceReference.AddDeviceRequest();
            inValue.Body = new MapWinFormsApplication.ServiceReference.AddDeviceRequestBody();
            inValue.Body.deviceName = deviceName;
            inValue.Body.longitude = longitude;
            inValue.Body.latitude = latitude;
            inValue.Body.cityName = cityName;
            inValue.Body.zoomLevel = zoomLevel;
            MapWinFormsApplication.ServiceReference.AddDeviceResponse retVal = ((MapWinFormsApplication.ServiceReference.WebServiceSoap)(this)).AddDevice(inValue);
            return retVal.Body.AddDeviceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapWinFormsApplication.ServiceReference.GetDevicesResponse MapWinFormsApplication.ServiceReference.WebServiceSoap.GetDevices(MapWinFormsApplication.ServiceReference.GetDevicesRequest request) {
            return base.Channel.GetDevices(request);
        }
        
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel[] GetDevices() {
            MapWinFormsApplication.ServiceReference.GetDevicesRequest inValue = new MapWinFormsApplication.ServiceReference.GetDevicesRequest();
            inValue.Body = new MapWinFormsApplication.ServiceReference.GetDevicesRequestBody();
            MapWinFormsApplication.ServiceReference.GetDevicesResponse retVal = ((MapWinFormsApplication.ServiceReference.WebServiceSoap)(this)).GetDevices(inValue);
            return retVal.Body.GetDevicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapWinFormsApplication.ServiceReference.GetCitiesResponse MapWinFormsApplication.ServiceReference.WebServiceSoap.GetCities(MapWinFormsApplication.ServiceReference.GetCitiesRequest request) {
            return base.Channel.GetCities(request);
        }
        
        public MapWinFormsApplication.ServiceReference.Entity2ViewModel[] GetCities() {
            MapWinFormsApplication.ServiceReference.GetCitiesRequest inValue = new MapWinFormsApplication.ServiceReference.GetCitiesRequest();
            inValue.Body = new MapWinFormsApplication.ServiceReference.GetCitiesRequestBody();
            MapWinFormsApplication.ServiceReference.GetCitiesResponse retVal = ((MapWinFormsApplication.ServiceReference.WebServiceSoap)(this)).GetCities(inValue);
            return retVal.Body.GetCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapWinFormsApplication.ServiceReference.GetDevicesByCityResponse MapWinFormsApplication.ServiceReference.WebServiceSoap.GetDevicesByCity(MapWinFormsApplication.ServiceReference.GetDevicesByCityRequest request) {
            return base.Channel.GetDevicesByCity(request);
        }
        
        public MapWinFormsApplication.ServiceReference.Entity1ViewModel[] GetDevicesByCity(string city) {
            MapWinFormsApplication.ServiceReference.GetDevicesByCityRequest inValue = new MapWinFormsApplication.ServiceReference.GetDevicesByCityRequest();
            inValue.Body = new MapWinFormsApplication.ServiceReference.GetDevicesByCityRequestBody();
            inValue.Body.city = city;
            MapWinFormsApplication.ServiceReference.GetDevicesByCityResponse retVal = ((MapWinFormsApplication.ServiceReference.WebServiceSoap)(this)).GetDevicesByCity(inValue);
            return retVal.Body.GetDevicesByCityResult;
        }
    }
}
